Add jenkinsfile
alphagov/govuk_taxonomy_helpers pull request #2
Opened 2017-02-16 16:09 UTC by MatMoore

2017-02-16 16:37 UTC, suzannehamilton requested changes
This all looks sensible to me, but I suspect you'll have to update the `bundleApp` step to get the build working on Jenkins.

2017-02-16 16:37 UTC, suzannehamilton commented on Jenkinsfile
> +REPOSITORY = 'govuk_taxonomy_helpers'
Unused constant?

2017-02-16 16:37 UTC, suzannehamilton commented on Jenkinsfile
> +      govuk.bundleApp()
We found on another gem that we couldn't use `bundleApp`. I think the problem was that it adds the `--deployment` flag, which isn't appropriate for a gem.

We used `sh("bundle install --path ${JENKINS_HOME}/bundles/${JOB_NAME}")` instead but we should probably extract it to the Jenkins helpers in govuk-puppet.

2017-02-16 17:53 UTC, MatMoore commented on Jenkinsfile
> +REPOSITORY = 'govuk_taxonomy_helpers'
I'm not sure actually, I can't find where this variable is used, but it's in the rails template Jenkinsfile, and gds-api-adapters (which I looked at as an example of another gem) also has it. 😕

2017-02-16 17:59 UTC, MatMoore commented on Jenkinsfile
> +      govuk.bundleApp()
Ah thanks, I'll look into extracting that then. Do you know if it's sufficient to just have `bundleGem` and `bundleApp` or do we use bundler in other ways?

2017-02-16 18:03 UTC, suzannehamilton commented on Jenkinsfile
> +REPOSITORY = 'govuk_taxonomy_helpers'
It's not in the [A/B testing gem Jenkinsfile](https://github.com/alphagov/govuk_ab_testing/blob/master/Jenkinsfile), and the rails template uses the constant in the integration deployment step. I'm not aware of any Jenkins magic that needs a `REPOSITORY` constant - I think it's safe to just delete.

2017-02-16 18:08 UTC, suzannehamilton commented on Jenkinsfile
> +      govuk.bundleApp()
I haven't seen any other uses of it, and it looks like [we're not using it in any other ways at the moment](https://github.com/search?l=Groovy&p=4&q=org%3Aalphagov+%22bundle+install%22&type=Code).

2017-02-17 10:30 UTC, MatMoore commented
@suzannehamilton Have extracted the bundle step in https://github.com/alphagov/govuk-puppet/pull/5502

2017-02-17 11:38 UTC, merged